### PR TITLE
Added Hourly Rotation Option, Added Rotator Option

### PR DESCRIPTION
**Pull request by windkit**

### CODE REVIEW

**Review by mocchira — CHANGES_REQUESTED** [review]
LGTM. One thing please define the custom behavior for Rotator for making the code easy to understand for maintainers and compilers to generate good error messages.

**Comment by mocchira** [comment]
@windkit `make test` got 2 failed as below on my dev-box
```
module 'lager_file_backend'
  lager_file_backend: get_loglevel_test...ok
  lager_file_backend: rotation_test_ (External rotation should work)...*failed*
in function undefined:ensure_logfile/4
  called as ensure_logfile("/tmp/lager_test/15855330/test.log",{file_descriptor,prim_file,{#Port<0.47922>,12}},1182563,{65536,1000})
in call from lager_file_backend:write/4 (src/lager_file_backend.erl, line 239)
in call from lager_file_backend:'-rotation_test_/0-fun-0-'/4 (src/lager_file_backend.erl, line 471)
in call from lager_file_backend:'-rotation_test_/0-fun-5-'/4 (src/lager_file_backend.erl, line 470)
**error:undef
  output:<<"">>

  lager_file_backend: rotation_test_ (Internal rotation and delayed write)...*failed*
in function undefined:ensure_logfile/4
  called as ensure_logfile("/tmp/lager_test/81267589/test.log",{file_descriptor,prim_file,{#Port<0.48500>,12}},1182563,{65536,1000})
in call from lager_file_backend:write/4 (src/lager_file_backend.erl, line 239)
in call from lager_file_backend:'-rotation_test_/0-fun-13-'/4 (src/lager_file_backend.erl, line 516)
**error:undef
  output:<<"">>
```
seems rotator is set to undefined?

**Comment by windkit** [comment]
@mocchira I have added the behavior definition and set the default value in the state record

**Review by mocchira — APPROVED** [review]

**Comment by mocchira** [comment]
@windkit LGTM. Thanks for your contribution.

**Pull request merged**
